# This is a Docker Compose configuration file for setting up services.
    # In this configuration, we define a PostgreSQL database service.

    services:
      db:
        # Specifies the Docker image to use for the PostgreSQL database.
        image: postgres:latest

        # Environment variables for the PostgreSQL database.
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password

        # Port mapping for the PostgreSQL database.
        ports:
          - "5432:5432" # Maps port 5432 on the host to port 5432 on the container.

        # Always restart the container if it stops.
        restart: always