spring.application.name=tasks

spring.datasource.driver-class-name=org.postgresql.Driver
# Use environment variables for connection details, with defaults for local testing
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:password}

# Automatically updates the database schema to match the entity models.
spring.jpa.hibernate.ddl-auto=update